[tools]
bun = "1.3.2"
npm = "11.6.3"
pkl = "0.27.2"
semver = "3.4.0"
usage = "2.8.0"
hk = "1.26.0"

[env]
_.path = [
    "{{config_root}}/node_modules/.bin",
]

[tasks]
build = "bun build ./src/index.ts --outdir dist --target bun"
test = "bun test"
lint = "eslint ."
"lint:fix" = "eslint . --fix"
format = "prettier --write ."
publish = "npm publish"
